/*
// Author: Xanieros
// Challenge Number: 2
// Challenge Description : Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
*/

#include <iostream>
using namespace std;

int main()
{
	int currentNumber = 2;
	int previousNumber = 1;
	int total = 0;
	do
	{
		int temp = currentNumber + previousNumber;
		if (currentNumber % 2 == 0)
			total += currentNumber;
		previousNumber = currentNumber;
		currentNumber = temp;
	} while (currentNumber < 4000000);
    cout << "The sum of the even-valued terms that do not exceed four million is " << total;
}